aliases:
  - &set_environment_variables
    run:
      name: Set environment variables
      command: |
        # set prefect tag -- currently pinning to master
        echo 'export PREFECT_VERSION=master' >> $BASH_ENV

  - &install_prefect_server
    run:
      name: Install Prefect Server
      command: |
        # Use the latest pip
        pip install --upgrade pip
        # install prefect master
        pip install --progress-bar off "git+https://github.com/prefecthq/prefect.git@${PREFECT_VERSION}"
        # install prefect server
        pip install --progress-bar off -e ".[dev]"
        cd services/apollo && npm install

  - &install_docker
    run:
      name: Install Docker client
      command: |
        set -x
        VER="18.09.3"
        curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
        tar -xz -C /tmp -f /tmp/docker-$VER.tgz
        rm /usr/local/bin/docker
        mv /tmp/docker/* /usr/bin

commands:
  prep_utils:
    description: "Checkout, Add SSH Keys, Get Testing Utilities (e.g. node)"
    steps:
      - add_ssh_keys
      - checkout
      - run:
          name: Install utilities
          command: |
            apt-get update
            # official binaries for nodejs
            curl -sL https://deb.nodesource.com/setup_14.x | bash -
            apt-get install -y sudo nodejs netcat
  prep_tests:
    description: "Run Prefect Server database migrations"
    steps:
      - run:
          name: Run Prefect Server database migrations
          command: prefect-server database upgrade --yes

executors:
  docker-prefect-server:
    docker:
      - image: python:3.7
        environment:
          PREFECT_SERVER__DATABASE__NAME: prefect_server
          PREFECT_SERVER__DATABASE__USERNAME: prefect
          PREFECT_SERVER__DATABASE__PASSWORD: pr343ct

      - image: "postgres:11"
        environment:
          POSTGRES_USER: prefect
          POSTGRES_PASSWORD: pr343ct
          POSTGRES_DB: prefect_server
        command: postgres -c max_connections=150

      - image: "hasura/graphql-engine:v2.0.9"
        command: /bin/sh -c "sleep 5 && graphql-engine serve"
        environment:
          HASURA_GRAPHQL_DATABASE_URL: postgres://prefect:prefect@localhost:5432/prefect_server
          HASURA_GRAPHQL_V1_BOOLEAN_NULL_COLLAPSE: "true"
          HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
          HASURA_GRAPHQL_SERVER_PORT: "3000"


version: 2.1
jobs:
  check_formatting:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run:
          name: Install Black
          command: pip install black
      - run:
          name: Run Black
          command: black --check .
      - run:
          name: Check for potentially unused imports
          command: |
            if [[ $(autoflake --remove-all-unused-imports -r --exclude __init__.py src | tee .unused-imports.txt | wc -c ) -ne 0 ]]; then
              echo "Potentially unused imports found"
              cat .unused-imports.txt
              exit 2
            fi

  run_unit_tests:
    executor: docker-prefect-server
    steps:
      - prep_utils
      - *set_environment_variables
      - *install_prefect_server
      - prep_tests
      - run:
          name: Run Server tests
          command: pytest -v -m "not (service_test or integration_test or migration_test)"

  run_database_migration_tests:
    executor: docker-prefect-server
    steps:
      - prep_utils
      - *set_environment_variables
      - *install_prefect_server
      - prep_tests
      - run:
          name: Run Server tests
          command: pytest -v -m migration_test

  run_service_tests:
    executor: docker-prefect-server
    steps:
      - prep_utils
      - *set_environment_variables
      - *install_prefect_server
      - prep_tests

      - run:
          name: Start Server services
          command: prefect-server dev services
          background: true
          env:
            - PREFECT__LOOP_SERVICE__DEBUG_MODE: true
      - run:
          name: Wait 10 seconds for services to start...
          command: sleep 10
      - run:
          name: Run Server service tests
          command: pytest -v -m service_test
          env:
            - PREFECT__LOOP_SERVICE__DEBUG_MODE: true

  run_integration_tests:
    executor: docker-prefect-server
    steps:
      - prep_utils
      - *set_environment_variables
      - *install_prefect_server
      - prep_tests

      - run:
          name: Configure credentials
          command: |
            mkdir ~/.config/gcloud/
            echo $GOOGLE_APPLICATION_CREDENTIALS_KEY > ~/.config/gcloud/integration-test-sa.json
            echo 'export GOOGLE_APPLICATION_CREDENTIALS=~/.config/gcloud/integration-test-sa.json' >> $BASH_ENV
      - run:
          name: Start Server services
          command: prefect-server dev services
          background: true
          env:
            - PREFECT__LOOP_SERVICE__DEBUG_MODE: true
      - run:
          name: Wait 10 seconds for services to start...
          command: sleep 10
      - run:
          name: Run Server integration tests
          command: pytest -v -m integration_test
          env:
            - PREFECT__LOOP_SERVICE__DEBUG_MODE: true
            
  publish_docker_images:
    machine:
      image: ubuntu-2204:2022.04.1
    environment:
      DOCKER_BUILDKIT: 1
      BUILDX_PLATFORMS: linux/amd64,linux/arm64
    steps:
      - run:  # https://circleci.com/blog/building-docker-images-for-multiple-os-architectures/
          name: Install buildx
          command: |
            BUILDX_BINARY_URL="https://github.com/docker/buildx/releases/download/v0.8.2/buildx-v0.8.2.linux-amd64"
            curl --output docker-buildx \
              --silent --show-error --location --fail --retry 3 \
              "$BUILDX_BINARY_URL"
            mkdir -p ~/.docker/cli-plugins
            mv docker-buildx ~/.docker/cli-plugins/
            chmod a+x ~/.docker/cli-plugins/docker-buildx
            docker buildx install
            # Run binfmt
            docker run --rm --privileged tonistiigi/binfmt:latest --install "$BUILDX_PLATFORMS"
      - run:
          name: Log in to docker hub
          command: |
            docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PW
      - run:
          name: Push apollo master tag
          command: |
            docker buildx build --push services/apollo -t prefecthq/apollo:master --platform $BUILDX_PLATFORMS --build-arg PREFECT_VERSION=master --build-arg RELEASE_TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          filters:
            branches:
              only: master
      - run:
          name: Push server master tag
          command: |
            docker buildx build --push . -t prefecthq/server:master --platform $BUILDX_PLATFORMS --build-arg PREFECT_VERSION=master --build-arg RELEASE_TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          filters:
            branches:
              only: master
      - run:
          name: Push apollo latest tag
          command: |
            docker buildx build --push services/apollo -t prefecthq/apollo:$CIRCLE_TAG -t prefecthq/apollo:latest --platform $BUILDX_PLATFORMS --build-arg PREFECT_VERSION=master --build-arg PREFECT_SERVER_VERSION=$CIRCLE_TAG --build-arg RELEASE_TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /(2\d{3}\.(0[1-9]|1[0-2])\.(0[1-9]|[12]\d|3[01])).*/
      - run:
          name: Push server latest tag
          command: |
            docker buildx build --push . -t prefecthq/server:$CIRCLE_TAG -t prefecthq/apollo:latest --platform $BUILDX_PLATFORMS --build-arg PREFECT_VERSION=master --build-arg PREFECT_SERVER_VERSION=$CIRCLE_TAG --build-arg RELEASE_TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /(2\d{3}\.(0[1-9]|1[0-2])\.(0[1-9]|[12]\d|3[01])).*/

orbs:
  docker: circleci/docker@1.0.0

workflows:
  version: 2
  "Check code style":
    jobs:
      - check_formatting

  "Run unit tests":
    jobs:
      - run_unit_tests
      - run_database_migration_tests

  "Run service & integration tests":
    jobs:
      - run_service_tests
      - run_integration_tests

  "Build and publish":
    jobs:
      - publish_docker_images
